export const mockCompanies = [
    {
      id: 'C001',
      name: 'Tech Corp',
      industry: 'Technology',
      status: 'Pending',
      email: 'contact@techcorp.com',
      phone: '123-456-7890',
      address: '123 Tech St',
      description: 'Leading tech company',
      website: 'https://techcorp.com',
      registrationDate: '2025-01-01',
    },
    {
      id: 'C002',
      name: 'Electro Inc',
      industry: 'Electronics',
      status: 'Approved',
      email: 'info@electroinc.com',
      phone: '987-654-3210',
      address: '456 Electro Ave',
      description: 'Innovative electronics',
      website: 'https://electroinc.com',
      registrationDate: '2024-12-15',
    },
  ];
  
  export const mockApplications = [
    {
      id: 'A001',
      companyId: 'C001',
      companyName: 'Tech Corp',
      status: 'Pending',
      registrationDate: '2025-01-01',
    },
    {
      id: 'A002',
      companyId: 'C002',
      companyName: 'Electro Inc',
      status: 'Approved',
      registrationDate: '2024-12-15',
    },
  ];
  
  export const mockInternships = [
    {
      id: 'I001',
      title: 'Software Intern',
      company: 'Tech Corp',
      location: 'Remote',
      type: 'Full-time',
      status: 'Open',
      description: 'Develop software solutions',
      requirements: 'JavaScript, React',
      postedDate: '2025-01-10',
      applyByDate: '2025-02-10',
      startDate: '2025-03-01',
      duration: '3 months',
      stipend: '$2000/month',
      url: 'https://techcorp.com/internship.pdf',
    },
    {
      id: 'I002',
      title: 'Hardware Intern',
      company: 'Electro Inc',
      location: 'On-site',
      type: 'Part-time',
      status: 'Closed',
      description: 'Design hardware circuits',
      requirements: 'Electronics, PCB Design',
      postedDate: '2024-12-01',
      applyByDate: '2024-12-31',
      startDate: '2025-01-15',
      duration: '6 months',
      stipend: '$1500/month',
      url: 'https://electroinc.com/internship.pdf',
    },
  ];
  
  export const mockReports = [
    {
      id: 'R001',
      studentId: 'S001',
      studentName: 'John Doe',
      reportType: 'Progress Report',
      major: 'Computer Science',
      submissionDate: '2025-02-01',
      status: 'Pending',
      companyName: 'Tech Corp',
      internshipTitle: 'Software Intern',
      reportUrl: 'https://techcorp.com/report.pdf',
    },
    {
      id: 'R002',
      studentId: 'S002',
      studentName: 'Jane Smith',
      reportType: 'Evaluation Report',
      major: 'Mechanical Engineering',
      submissionDate: '2025-01-15',
      status: 'Accepted',
      companyName: 'Electro Inc',
      internshipTitle: 'Hardware Intern',
      reportUrl: 'https://electroinc.com/report.pdf',
      supervisorName: 'Dr. Smith',
      internshipStartDate: '2024-11-01',
      internshipEndDate: '2025-01-15',
    },
  ];
  
  export const mockStudents = [
    {
      id: 'S001',
      name: 'John Doe',
      gucId: '43-1234',
      major: 'Computer Science',
      internshipStatus: 'Placed',
      email: 'john.doe@guc.edu',
      cvUrl: 'https://example.com/john-doe-cv.pdf',
    },
    {
      id: 'S002',
      name: 'Jane Smith',
      gucId: '43-5678',
      major: 'Mechanical Engineering',
      internshipStatus: 'Not Applied',
      email: 'jane.smith@guc.edu',
      cvUrl: null,
    },
    {
      id: 'S003',
      name: 'Alice Johnson',
      gucId: '43-9012',
      major: 'Electrical Engineering',
      internshipStatus: 'Completed',
      email: 'alice.johnson@guc.edu',
      cvUrl: 'https://example.com/alice-johnson-cv.pdf',
    },
  ];
  
  export const mockCycles = [
    {
      id: 'CY001',
      name: 'Summer 2025',
      startDate: '2025-06-01',
      endDate: '2025-08-31',
      status: 'Upcoming',
    },
    {
      id: 'CY002',
      name: 'Winter 2024',
      startDate: '2024-12-01',
      endDate: '2025-02-28',
      status: 'Active',
    },
  ];